#!/usr/bin/env python3
"""Emit the LaTeX body of the full-suite speedup table (paper appendix)
from shader_sweep_summary.csv."""
from __future__ import annotations

import csv
import sys
from pathlib import Path

LABELS = {
    "qft": "QFT",
    "qft_entangled": "QFT (entangled input)",
    "phase_estimation": "Phase estimation",
    "phase_estimation_inexact": "Phase estimation (inexact)",
    "grover": "Grover search",
    "ghz": "GHZ preparation",
    "qaoa": "QAOA (ring)",
    "graph_state": "Graph state",
    "deutsch_jozsa": "Deutsch--Jozsa",
    "ae": "Amplitude estimation",
    "quantum_walk": "Quantum walk",
    "quantum_walk_vchain": "Quantum walk (v-chain)",
    "wstate": "W state",
    "variational": "Variational ansatz",
    "qcbm": "QCBM",
    "vqe": "VQE ansatz + energy",
    "realamp": "RealAmplitudes",
    "su2rand": "EfficientSU2 (random)",
    "qnn": "QNN layer",
    "random_circuit": "Random circuit",
    "cuquantum_blueqat": "cuQuantum/blueqat proxy",
    "hamiltonian": "TFIM Trotter (1st order)",
    "tfim_trotter2": "TFIM Trotter (2nd order)",
    "tfim_random_field": "TFIM random field",
    "heisenberg": "Heisenberg chain",
    "heisenberg_xxz": "Heisenberg XXZ",
    "heisenberg_random_field": "Heisenberg random field",
    "ladder_heisenberg": "Heisenberg 2-leg ladder",
    "long_range_ising": "Long-range Ising",
}


def fmt_ms(v: float) -> str:
    if v >= 10000:
        return f"{v/1000:.1f}\\,s"
    if v >= 1000:
        return f"{v/1000:.2f}\\,s"
    return f"{v:.1f}\\,ms"


def main() -> int:
    outdir = Path(sys.argv[1])
    rows = list(csv.DictReader(
        (outdir / "shader_sweep_summary.csv").open()))
    rows.sort(key=lambda r: -float(r["paired_ratio_mean"]))
    print("% generated by tools/gen_sweep_table.py from", outdir)
    for r in rows:
        name = LABELS.get(r["benchmark"], r["benchmark"])
        ratio = float(r["paired_ratio_mean"])
        lo, hi = float(r["paired_ratio_min"]), float(r["paired_ratio_max"])
        print(f"{name} & {fmt_ms(float(r['pure_mean_ms']))} & "
              f"{fmt_ms(float(r['metal_mean_ms']))} & "
              f"${ratio:.1f}\\times$ & $[{lo:.1f}, {hi:.1f}]$ \\\\")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
